### ISSUE TITLE
Next 13.4 App & Pages Routes co-usage

### ISSUE THREAD

**Issue by sheiman-pavlo** [aralroca/next-translate#1044]
**What version of this package are you using?**

```json
"next": "13.4.1",
"next-translate": "^2.0.5",
```

**What operating system, Node.js, and npm version?**

CSB: https://codesandbox.io/p/sandbox/funny-heisenberg-d5cwo6

**What happened?**

As per Next 13+, you can use legacy pages and new app router at the same time, allowing incremental adaptation. When next-translate is used on such project, with `appDir: true` in the next config, only app router pages are translated.

MRR: https://codesandbox.io/p/sandbox/funny-heisenberg-d5cwo6

See index page live in app dir, and second page live in the pages dir. i18n implementation is same for both, but only app router page picks up the translation. 

This also confirmed by logger:

```
next-translate - compiled page: / - locale: en - namespaces: common - used loader: force-dynamic (server page)
``` 

But no logger record when you visit legacy router page.

App router page: https://d5cwo6-3000.csb.app/
Pages router page: https://d5cwo6-3000.csb.app/legacy-router

**What did you expect to happen?**

Both pages could be translated and have access to all configured namespaces.

**Are you willing to submit a pull request to fix this bug?**

Not sure of the cause.

**Comment by alvesvin** [comment]
I'm having this same issue.  I need this as soon as possible so I'm willing to give it a try on contributing to the solution. Note this would be my first time contributing to open source, so I need guidance.  

From what I've been looking in this project, the solution could be to inject next-translate as a page by page basis in next-translate-plugin rather than a general isNext13App for all pages.

I'm going to explore a little more, but if @aralroca read this and is willing to put his own perspective I'd be appreciated.

**Comment by aralroca** [comment]
It seems better to me that it is in the [`next-translate-plugin`](https://github.com/aralroca/next-translate-plugin/issues/21). I close this one and have it reported there better, thanks.
