### ISSUE TITLE
Namespace containing flat keys only being loaded if using a `loadLocaleFrom`-fn

### ISSUE THREAD

**Issue by boredland** [aralroca/next-translate#1064]
**What version of this package are you using?**

2.0.6, but also gave 2.3.0-canary.3 a try

**What happened?**

According to the README, to use flat keys inside the locales instead of nested ones, one has to set `keySeparator: false`. For me this leads to nothing being translated. By accident I found a way of this still working: when using a loader function.

**What did you expect to happen?**

Flat keys to be picked up.

**Are you willing to submit a pull request to fix this bug?**

Sure, but first I created a reproduction: https://github.com/boredland/next-translate/tree/repro/nested-keys-only-with-loader

You can try the failing variant by disabling/removing the `loadLocaleFrom`.

**Comment by aralroca** [comment]
Ok, looks like a bug then. `keySeparator` to `false` should work. Add free to add the failing case + fix it. Otherwise, I'm going to fix it another day! Thanks for the report @boredland!

**Comment by boredland** [comment]
I had a quick look already and didn't immediately catch how the default loader, when no "loadLocaleFrom" is being passed, is being configured, seeing some kinda confusing falling back to `Promise.resolve({})` - will have a look next week again, I guess.

**Comment by aralroca** [comment]
@boredland I added some tests but I do not get the failing case, all pass well... Can be related to another thing? Should be cool to create a reproducible example. Thanks.

**Comment by boredland** [comment]
Didn't my case above just fail when removing the loader? When I tried it earlier, it behaved like that.

**Comment by boredland** [comment]
Just gave it another try:

[recording_20230610-104447.webm](https://github.com/aralroca/next-translate/assets/4662748/5edfef54-7df1-4408-8d79-03586d052339)

**Comment by aralroca** [comment]
Wow... Very rare behavior... Thanks to detect it. Let's see what is happening

**Comment by aralroca** [comment]
@boredland The behaviour I see only happens when changing the `i18n.js` file with hotreloading open. What happens is that the plugin that is executed during the next.config.js needs to know if it has its own `loadLocaleFrom` or uses the default, at the moment it changes, it doesn't know and that's why it stops working. Everything should be corrected by closing yarn dev and running yarn dev again.

This doesn't happen only with `flat.keys`,  it happens with all of them. In the video you sent me you can see that it also happens with the title.

However, I have taken the opportunity to improve the detection of `loadLocaleFrom` and now in pre-release [2.3.0-canary.4](https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.4) it should work correctly.
