### ISSUE TITLE
Page crashes

### ISSUE THREAD

**Issue by alirezas** [aralroca/next-translate#1085]
**What version of this package are you using?**
```
"next-translate": "2.4.0",
"next-translate-plugin": "2.4.0",
```

**What operating system, Node.js, and npm version?**

v18.16.0

**What happened?**
When i use `const { t } = useTranslation()` in nested components getting a warning in console like this: `You forgot to pass the "pathname" inside "loadNamespaces" configuration` and browser get crashed.

Bug reproduced here:
https://codesandbox.io/p/sandbox/dreamy-firefly-6c9p3y

**Comment by aralroca** [comment]
I just try it your reproduced example, but I can't visualize the error. It's displayed this into the web:

<img width="505" alt="Screenshot 2023-06-24 at 12 21 43" src="https://github.com/aralroca/next-translate/assets/13313058/a1d0cc7a-170d-4475-abe8-8b65106e32f6">

Looks good because is the translated text:

<img width="292" alt="Screenshot 2023-06-24 at 12 23 06" src="https://github.com/aralroca/next-translate/assets/13313058/336950cd-7064-48ca-9c3e-67d730b50ef4">

And any error on the console:

<img width="969" alt="Screenshot 2023-06-24 at 12 23 43" src="https://github.com/aralroca/next-translate/assets/13313058/9532c3b7-1ea7-4535-89db-bfe08649bb5d">

@alirezas can you provide more details about how to reproduce it? Thanks

**Comment by alirezas** [comment]
I changed example and added a react-query call. it will stuck and crash.

**Comment by aralroca** [comment]
Thanks to report it @alirezas. I'm investigating how to fix it. I see that to fix temporally this waterfall for now you have to add a `Suspense` above.

```js
<Suspense>
  {data.map((item, idx) => (
    <ListItem item={item} key={idx} />
  ))}
</Suspense>
```


 Even so, I don't think there should be any need for this `Suspense`... I am sure we will find a more efficient way to ensure that the namespaces are properly hydrated in the client components.

**Comment by aralroca** [comment]
Ok, I've got an idea on how to solve it. Ideally, the namespace should only be loaded once at the page level and then no code conversion is needed in the webpack plugin at the component level. To make it compatible at both RSC and RCC level, you can load it with a wrapper that works with RCC but then as it renders the children, its children can be RSC and I understand that this would solve this problem. I'll look at implementing it later and give some feedback, but I really think this will simplify the current webpack plugin and at the same time avoid you having to put the Suspense for each client component that consumes translations.

**Comment by aralroca** [comment]
@alirezas please try:

- Next-translate: [`2.4.1`](https://github.com/aralroca/next-translate/releases/tag/2.4.1)
- Next-translate-plugin: [`2.4.1`](https://github.com/aralroca/next-translate-plugin/releases/tag/2.4.1)

And give feedback if is working now in your case! Thanks!

**Comment by alirezas** [comment]
@aralroca yup! it solved my problem... Thanks!

**Comment by aralroca** [comment]
Thank you for your contribution reporting this error @alirezas 🙏
