### ISSUE TITLE
Redirect in middleware does not work with Next Translate

### ISSUE THREAD

**Issue by EricImpact** [aralroca/next-translate#1106]
**What version of this package are you using?**

- Next Translate `2.4.4`
- Next Translate Plugin `2.5.0-canary.2`

**What operating system, Node.js, and npm version?**

- MacOS Ventura `13.4`
- Node `18.16.0`

**What happened?**

After setting up a basic site with Next Translate working in the app directory with Next `13.4.7`, and with server & client components both displaying translations, I created middleware to try to have any request that misses a locale redirect to the same path with the locale prepended. 

With the middleware created, any request to a page missing the locale (e.g. `http://localhost:3000` or `http://localhost:3000/login`) results in a redirect loop. 

**What did you expect to happen?**

I want requests missing a locale to automatically redirect to the same path with the locale prepended. In other words, a request to `http://localhost:3000` redirects to `http://localhost:3000/en/` and a request to `http://localhost:3000/login` redirects to `http://localhost:3000/en/login/`. 

This is the pattern used in https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing and I have confirmed that works in the way I described with vanilla Next.js. 

I expect it to work in the same way with Next Translate. 

**Are you willing to submit a pull request to fix this bug?**

Yes, though I have no idea where/how Next Translate is interfering with the redirect/middleware.

**Comment by EricImpact** [comment]
I forgot to add, I have a sample repo up at https://github.com/EricImpact/next-translate-example/ which shows how I'm approaching this.

**Comment by aralroca** [comment]
This is related with this issue from Next.js https://github.com/vercel/next.js/issues/49883 we can't solve it in this package. As a solution, I proposed an alternative in next-translate [v2.3 release](https://github.com/aralroca/next-translate/releases/tag/2.3.0) to solve this meanwhile the Next.js team doesn't fix this.

I'm going to close the issue because we can't fixed in our side. Please comment this inside this issue https://github.com/vercel/next.js/issues/49883. Thanks to report it anyway!
