### ISSUE TITLE
Interpolation formatting

### ISSUE THREAD

**Issue by karianpour** [aralroca/next-translate#266]
Is there a way to format the interpolation? The way [`i18next`](https://www.i18next.com/translation-function/formatting) does it is very convenient. For example dates and number should be formatted differently in different languages.

```
{
  "variable-example": "Using a variable {{price, decimal}}"
}
```
```
t('common:variable-example', { price: 1234 })
```
```
// somehow we have to let the next-translate know this function
interpolation: {
  format: function (value, format, lng) {
    if(format === 'decimal') return decimalFormat(value, lng);
    return value;
  }
}
```
the result should be:
en:
```
Using a variable 1,234
```
de:
```
Using a variable 1.234
```
fa:
```
Using a variable ۱،۲۳۴
```

**Comment by aralroca** [comment]
Not in the next-translate API, we have a basic i18n support, however, you can do it with:

```js
const formatters = {
  es: new Intl.NumberFormat("es-ES"),
  en: new Intl.NumberFormat("en-EN"),
}

t('common:variable-example', { price: formatters[lang](1234) })
```

**Intl.NumberFormat** is supported in all browsers: https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Intl/NumberFormat

**Comment by karianpour** [comment]
@aralroca Thanks, that is a nice approach.

**Comment by j-schumann** [comment]
Hello @aralroca,

I would like to bring this up again: While the suggested approach works for many/simple cases it is not convenient for multiple reasons:

a) I would like to be able to let the translator decide if e.g. in this case the date should be displayed in short or long format by using `you registered at {{value, shortDate}}` or `you registered at {{value, longDate}}`, with or without time or if a number should be displayed with or without decimals. This could be done if the translator could simply change the formatter in the JSON file without having to ask the developer to change it in all required places

b) The suggested approach requires to duplicate the inclusion of the necessary formatters in each file where a translation is used, without using additional helper code this would mean including those 4 lines defining the formatter in each JSX/component file that wants to format numbers.

c) Also it makes it difficult to change the format for a translation that is used in multiple files because it probably cannot changed using search&replace when a parameter with the same name / formatting is used for a different translation that should not be changed.

d) It gets confusing quickly to see how something is displayed if multiple parameters with formatting are used. E.g. `Your order {{orderId}} from {{orderDate, shortDate}} was shipped, {{orderTotal, currency}} including {{orderVat, percent}} was billed` is easy to read & understand, while applying the formatters manually probably wouldn't.

e) It prevents caching of formatters used multiple times, a centralized formatter for the interpolation could re-use Intl.NumberFormat instances etc.

Can we please add this as feature request for v1.1 ?

**Comment by aralroca** [comment]
@j-schumann Ok, I reopen it and reconsider it. It makes sense what you said.👍

**Comment by j-schumann** [comment]
Hello @aralroca,

I have a rudimentary implementation here: https://github.com/j-schumann/next-translate/commit/31bc4e0f28f8a670f429059989cb006bd572efd4

The main part that is missing is supplying the current locale to the user's formatter function. How can we get the language into the interpolation function or even into the t() function?

What do you think?

**Comment by aralroca** [comment]
@j-schumann Great! Feel free to do PR. Thanks for your effort 🙏

**Comment by j-schumann** [comment]
Do you have any suggestions on how to get the locale into the formatter function? WIthout this the feature is probably not very useful. Maybe wrap the user-supplied function in `I18nProvider` with something like:

```
if (typeof config?.interpolation?.format === "Function") {
    config.interpolation.format = (text, format) => config.interpolation.format(text, format, lang)
}
```
where `lang` comes from L18: `const lang = lng || parentLang || locale || defaultLocale || ''``?

But is this sufficient for all use cases, probably not for `getT` because it does not use the I18nProvider?

**Comment by aralroca** [comment]
@j-schumann I think the simple way is to modify this line:

https://github.com/vinissimus/next-translate/blob/1.0.1/src/I18nProvider.tsx#L26

to:

```js
 const t = transCore({ config, allNamespaces, pluralRules, lang }) // adding the lang
```

Until now it was not needed inside the `transCore`, but if needed, it can be added.

**Comment by aralroca** [comment]
Formatters are already supported in next-translate new versions: https://github.com/aralroca/next-translate#9-formatter
