### ISSUE TITLE
Loader problems with commented code

### ISSUE THREAD

**Issue by foldess** [aralroca/next-translate#753]
Just wanted to notify (not sure if it's already known) that if there is an commented "getServerSideProps" on a page and a non commented one, the app fails to compile with ```Identifier 'getServerSideProps' has already been declared.``` error.
This only happens if the commented "getServerSideProps" appears before the non commented one in the code. I haven't tested with other methods, it just happened to me by chance because i commented mine and wrote another one to test and it turned out into this bug

```
// export async function getServerSideProps(context) {
// 	return {}
// }

export async function getServerSideProps(context) {
	return {
	}
}
```

**Comment by aralroca** [comment]
Looks that is because here:

https://github.com/vinissimus/next-translate/blob/bd2639f4fd24b973cca8a5c022665a45a1a9345a/src/plugin/loader.ts#L105

Is using `rawCode` instead of `code` (without comments):

https://github.com/vinissimus/next-translate/blob/bd2639f4fd24b973cca8a5c022665a45a1a9345a/src/plugin/loader.ts#L42

When I'm at the computer I'll try to create the failing test and see if it's because of that (it looks like it). If you are in a hurry feel free to do a PR.

**Comment by aralroca** [comment]
Solved in 1.3.2

**Comment by aralroca** [comment]
I reopen because 1.3.2 causes conflicts and I revert it in 1.3.3. So now this issue should be fixed with a different approach.

**Comment by aralroca** [comment]
Related: https://github.com/vinissimus/next-translate/issues/769

**Comment by aralroca** [comment]
@foldess The idea of 2.0 version is to change the regular expressions in a better way. Currently, there are 2 proposals: with Babel parser and with TypeScript compiler.

We need feedback from the people to decide which one corrects more errors and does not generate new ones.

This bug should be fixed with the new version. Can you test these two prereleases and give feedback?

**With Babel**: [2.0.0-experimental.1](https://github.com/aralroca/next-translate/releases/tag/2.0.0-experimental.1)

**With TypeScript compiler**: [2.0.0-experimental.2](https://github.com/aralroca/next-translate/releases/tag/2.0.0-experimental.2)

You can use this discussion to write your feedback:

https://github.com/aralroca/next-translate/discussions/881

Thank you so much!

**Comment by aralroca** [comment]
This should work in 2.0.0-canary.1. I close the issue. Feel free to reopen / comment if is not solved
