### ISSUE TITLE
translation don't work with export { IMPORT as default }

### ISSUE THREAD

**Issue by j3sch** [aralroca/next-translate#827]
My Component:
`export  function LoginForm() {
...
}
`

On the page I then use:
`export { LoginForm as default } from '~/components/Login/LoginForm';`
to display my component.

**Comment by finkrer** [comment]
Same here.
```js
export { default, getServerSideProps } from 'components/analytics/DashboardPage'
```
Works perfectly except for translations. All the keys are reported as missing in the console.

**Comment by aralroca** [comment]
@j3sch @finkrer The idea of 2.0 version is to change the regular expressions in a better way. Currently, there are 2 proposals: with Babel parser and with TypeScript compiler.

We need feedback from the people to decide which one corrects more errors and does not generate new ones.

This bug should be fixed with the new version. Can you test these two prereleases and give feedback?

**With Babel**: [2.0.0-experimental.1](https://github.com/aralroca/next-translate/releases/tag/2.0.0-experimental.1)

**With TypeScript compiler**: [2.0.0-experimental.2](https://github.com/aralroca/next-translate/releases/tag/2.0.0-experimental.2)

You can use this discussion to write your feedback:

https://github.com/aralroca/next-translate/discussions/881

Thank you so much!

**Comment by aralroca** [comment]
> The TypeScript version works as intended.

Amazing! great!

> Also, isn't Babel being phased out by Next in favor of their own compiler? Not sure if it's the same thing, but if so, depending on Babel probably isn't a good idea.

in theory no, because they are two different builds, as @StLyn4 commented [here](https://github.com/aralroca/next-translate/discussions/881#discussioncomment-3728444
).

I encourage you to leave your feedback in [this discussion](https://github.com/aralroca/next-translate/discussions/881) for the record. For version 2.0 at the moment people seem to like the Typescript compiler more, let's see if we make version 2.0 before the end of this year.

**Comment by aralroca** [comment]
Typescript version is already in Next-translate 2.0 😊
