### ISSUE TITLE
Automatically add hreflang-links

### ISSUE THREAD

**Issue by Ainias** [aralroca/next-translate#895]
**What version of this package are you using?**
1.5.0

**What problem do you want to solve?**
When a site is translated in different languages, it should inform search engine crawlers about the other languages. 
Since next-translate is already altering the pages, it should be possible to insert the `<link rel="alternate" hreflang="lang_code" href="url_of_page" />` for every locale automatically.

**What do you think is the correct solution to this problem?**
Out of my head, I would say add a component which does exactly that, using Next/Head, the current route and the locales

**Are you willing to submit a pull request to implement this change?**
Maybe, i'm not sure when I will find the time for this

**Comment by aralroca** [comment]
This is off-target behavior for the library. It is currently possible to implement it, but each project may use the `hreflang` differently (different subdomains, etc). It is best to let everyone adapt it to their needs.

**Comment by Ainias** [comment]
But is'nt that configured inside the config? As far as I know there are only two options, with different (sub-)domains or within the path. I think that most users use one of the two possibilites and those two should be easy to implement. 
The hreflang-links should be optional, since some projects don't have different sites for different languages, but that would be only a small amount.

**Comment by aralroca** [comment]
there can be mixtures, pages that are migrated to a new site and pages that are not yet migrated. Also instead of subdomini a different domini (as in the case of vinissimus.com or vinissimus.it), etc. 

Besides, in each language the page can have a different name if you use getStaticPaths (`/en/cart` and `/es/carrito`). And also all [redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects) and [rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites) should be taken into account.

It is implementing a lot of complexity out of scope, when later each project will have its implementation of this.

**Comment by aralroca** [comment]
However @Ainias, even if it is not the goal of this library, feel free to create a library that does it. In fact it is not so much related to next-translate, so other people who use other libraries to translate pages (like reacti18next) can use it too.

**Comment by Ainias** [comment]
That makes sense, thanks for explaining it :)
