### ISSUE TITLE
You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`

### ISSUE THREAD

**Issue by Lucasvo1** [aralroca/next-translate#965]
**What version of this package are you using?**
1.6.0

**What happened?**
I am getting this error when compiling my project:

**Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`**

I have not used getInitialProps, so I don't know where this comes from.

**Comment by aralroca** [comment]
Are you using a HOC in `_app.js`? 

as it says in the documentation:

> getInitialProps. This is the default method for these pages that use a HoC. This is in order to avoid conflicts because HoC could overwrite a getInitialProps.

This is because we use regex in the webpack plugin and it would be solved in version [2.0.0-experimental.3](https://github.com/aralroca/next-translate/releases/tag/2.0.0-experimental.3) that we have changed the regex for the TypeScript compiler. Could you confirm that with this experimental version it works correctly? Thanks! 😊

**Comment by Lucasvo1** [comment]
For me it's working with the new version. Thanks a lot.

**Comment by aralroca** [comment]
In this case, I close the issue, and very soon will be version 2.0.0-canary.1 with these changes, we have already decided to stop being experimental and this is the correct behavior of the plugin for Next-translate 2.0.0
