### ISSUE TITLE
Can't switch default locale

### ISSUE THREAD

**Issue by monosolar** [aralroca/next-translate#972]
**What version of this package are you using?**
next-translate 1.6.0

**What operating system, Node.js, and npm version?**
Mac OS 12.4, Node JS 18.0.0, npm 8.6.0

**What happened?**
Can't switch default locale to other than en.
"defaultLocale": "de": http://localhost:3000 -> http://localhost:3000/**en**

**What did you expect to happen?**
"defaultLocale": "de": http://localhost:3000 -> http://localhost:3000/**de**

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by aralroca** [comment]
All the i18n routing is part of Next.js core, not from this library. I invite you to take a look at the documentation:

https://nextjs.org/docs/advanced-features/i18n-routing

Probably you need to disable the automatic locale detection

```diff
{
    locales: ['default', 'en', 'de', 'fr'],
    defaultLocale: 'default',
+    localeDetection: false,
  },
```

Docs: https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale

I am closing the issue as it is not part of this library. If you have any problem with the routing part of i18n you have to report it directly to the Next.js repository.

**Comment by raul-potor** [comment]
For anyone wondering why this is happening, it's because Next.js uses the accept-language header sent by the user's browser to determine their preferred language. If the user's preferred language is not the same as the site's `defaultLocale`, Next.js will redirect them to a URL with the `defaultLocale `value as the prefix. 

To avoid this behaviour, you can disable locale detection altogether by setting localeDetection to false as aralroca said
